server:
  port: 3000

  # 데이터베이스 설정
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project
    username: ${db.username}
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddlAuto: create

  jackson:
    serialization:
      failOnEmptyBeans: false

# 
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# 오픈 API 서비스 키
openApi:
  serviceKey: ${openApi.serviceKey}
